name: Merge upstream branches
on:
  schedule:
    - cron:  "50 15 * * *"
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pulls from upstream
        run: |
          git config --global user.name 'rgodha24'
          git config --global user.email 'rgodha24@users.noreply.github.com'

          git pull "https://github.com/201-991-Broncobotics/broncobotics-website.git" 
          git push "https://github.com/rgodha24/broncobotics-website.git"
